### ISSUE TITLE
Fails to compile on 0.13.2

### ISSUE THREAD

**Issue by smpallen99** [josephwilk/amrita#103]
I get the following error:

== Compilation error on file lib/amrita/formatter/documentation.ex ==
*\* (CompileError) lib/amrita/formatter/documentation.ex:10: cannot import ExUnit.Formatter.format_test_failure/6 because it doesn't exist
    (elixir) src/elixir_import.erl:58: :elixir_import.calculate/6
    (elixir) src/elixir_import.erl:20: :elixir_import.import/4
    (elixir) src/elixir_exp.erl:122: :elixir_exp.expand/2
    (stdlib) lists.erl:1352: :lists.mapfoldl/3
    (stdlib) lists.erl:1353: :lists.mapfoldl/3
    (elixir) src/elixir_exp.erl:49: :elixir_exp.expand/2
    (elixir) src/elixir.erl:188: :elixir.quoted_to_erl/3
    (elixir) src/elixir.erl:157: :elixir.erl_eval/2

could not compile dependency amrita, mix compile failed. You can recompile this dependency with `mix deps.compile amrita` or update it with `mix deps.update amrita`
