### ISSUE TITLE
Fails to compile on elixir 0.14.3

### ISSUE THREAD

**Issue by ritalin** [josephwilk/amrita#112]
got below compile error:

```
== Compilation error on file lib/amrita/checkers/exceptions.ex ==
** (CompileError) lib/amrita/checkers/exceptions.ex:24: invalid rescue clause. The clause should match on an alias, a variable or be in the `var in [alias]` format
    (elixir) src/elixir_exp_clauses.erl:22: :elixir_exp_clauses.clause/5
   …
```

Following by "https://groups.google.com/forum/#!topic/elixir-lang-talk/KUgeG3umQ1Y", compile error has resolved.

But then other error has occurred.

```
== Compilation error on file lib/amrita/checkers/collection.ex ==
** (CompileError) lib/amrita/checkers/collection.ex:53: cannot invoke local is_record/2 inside guard
    (stdlib) lists.erl:1352: :lists.mapfoldl/3
    …
```

it seems for is_record function to due to be deprecated in elixir 0.13.3.
Replacing to is_map, this error has resolved.

Simiraly, fixed at "lib/amrita/checkers/collection.ex:96" too.

But compile error involved deprecation has occurred yet…
